### ISSUE TITLE
Congnitive Speech service SDK not resolved.

### ISSUE THREAD

**Issue by shobhitjdpsr** [compulim/web-speech-cognitive-services#107]
Hi

I am getting the following errors while using import createponyfil.....    statement and trying to build my solution:-
@compulim 

Severity    Code    Description    Project    File    Line    Suppression State
 Error        Can't resolve 'microsoft-cognitiveservices-speech-sdk/distrib/lib/microsoft.cognitiveservices.speech.sdk' in 'C:\Users\abc\source\repos\abc\source\Clients\abc\abcRoleUX\node_modules\web-speech-cognitive-services\lib\SpeechServices'    WebRoleUX    C:\Users\abc\source\repos\abc\source\Clients\def\abcRoleUX\Module not found

Any leads would be appreciated!

**Comment by compulim** [comment]
You must install `microsoft-cognitiveservices-speech-sdk` when you install this package. They are [peer-depended](https://nodejs.org/en/blog/npm/peer-dependencies/). You probably missed the warning when you `npm install` this package.

We prefer peer dependency model so you can select any supported versions of `microsoft-cognitiveservices-speech-sdk` and not locked down to a single version.
