### ISSUE TITLE
Save and Download

### ISSUE THREAD

**Issue by TwinMist** [compulim/web-speech-cognitive-services#115]
Hi, Using your example how would you go about saving the recording to the server and prompting the user to download it?
many thanks

**Comment by TwinMist** [comment]
Hi
When downloading the voice is different to the one selected and played thought the speakers when you click on start synthesis 
is this able to match the selected voice
thanks

**Comment by TwinMist** [comment]
sorted
speechConfig.speechSynthesisVoiceName = voiceOptions.value;
was missing from downloadButton.addEventListener function

**Comment by compulim** [comment]
This is for polyfilling W3C Web Speech API with Azure Cognitive Services.

Since W3C Web Speech API does not support downloading, this package will not support it either.
