### ISSUE TITLE
Setting maxalternatives

### ISSUE THREAD

**Issue by arun7sun** [compulim/web-speech-cognitive-services#83]
@compulim , How to set maxalternatives for speech recognition? Is there any way

**Comment by compulim** [comment]
Yes, `maxAlternatives` is supported. You can refer to [this MDN article](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/maxAlternatives) to set the `maxAlternatives` property.

However, as I tested, Cognitive Services only returns 5 alternatives. So setting it > 5 will only return up to 5 results.
