### ISSUE TITLE
Can we use this library in angular app

### ISSUE THREAD

**Issue by saisandeeppalla** [compulim/web-speech-cognitive-services#84]
I am trying to use this library in angular but getting exception that web_speech_cognitive_services_lib_SpeechServices__WEBPACK_IMPORTED_MODULE_5__ is not a function

**Comment by compulim** [comment]
It seems your import statement is incorrect. Please see the following.

```js
import { createSpeechRecognitionPonyfill } from 'web-speech-cognitive-services/lib/SpeechServices/SpeechToText';
```
